import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["vietnamese"], variable: "--font-inter" });
import { StrictMode } from "react";
export const metadata: Metadata = {
    title: "Shippy giao hàng",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`font-sans`} suppressHydrationWarning={true}>
                {children}
            </body>
        </html>
    );
}
